### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by chengxuanying** [ChuanMeng/RefNet#2]
Hi Chuan,

I noticed that R1 is significantly higher than other baselines as you mentioned in Table1, while R2 shows the opposite trending.
Could you give a deeper discussion?

Best,
Chengxuan

**Comment by ChuanMeng** [comment]
Hey Chengxuan,
Sorry for the late reply. This is a question that also makes me confused. I speculate that this is because the advantage of extraction method. Concretely, you can see that the generation methods are always below than extraction methods in terms of R2, and RefNet is higher than these pure generation methods but slightly below these pure extraction methods.
